name: CI

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - ocaml-base-compiler.4.12.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: ${{ matrix.os != 'macos-latest' }}
          opam-depext-flags: --with-test

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build @install

      - name: build-doc
        if: github.ref == 'refs/heads/main'
        run: |
          opam install odoc
          opam exec -- dune build @doc

      - name: deploy-doc
        uses: JamesIves/github-pages-deploy-action@3.6.2
        if: github.ref == 'refs/heads/main'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build/default/_doc/_html
          CLEAN: true

  lint-fmt:
    strategy:
      matrix:
        ocaml-compiler:
          - ocaml-base-compiler.4.12.0

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - run: opam depext ocamlformat --install

      - run: opam install . --deps-only

      - run: opam exec -- dune fmt

